### ISSUE TITLE
Markdown validator wasn't working

### ISSUE THREAD

**Issue by CinthyaRivera** [Fiserv/firstvision-latam#5]
Markdown validator wasn't working so I fixed and now I don't get any error but still can't see my changes on dev portal.

Also, in other tenant (acquiring) when something is wrong it shows a link to markdown documentation but here it's not happening.

**Comment by TaniaSarkar89** [comment]
@CinthyaRivera please do not create issues in your repositories. 
You can use the below 'Help' section from developer studio application to create issues in our "Support" Repository.

<img width="1718" alt="image" src="https://user-images.githubusercontent.com/74629095/208114165-24aeafe6-bd47-4687-8594-25b323b3cba8.png">

**Comment by CinthyaRivera** [comment]
Got it. Thanks
